sudo: required
group: deprecated-2017Q4
language: python
python:
    - "2.7"
env:
    - CKANVERSION=2.8
    - CKANVERSION=2.7
    - CKANVERSION=2.6
    - CKANVERSION=2.5
    - CKANVERSION=2.4
install:
    - bash bin/travis-build.bash
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
services:
    - postgresql
script: sh bin/travis-run.sh
before_install:
    - pip install codecov
after_success:
    - codecov
